## MACBOOK HOST VARS
##
## Host variables for the macbook host
## =============================================================================

## Ansible host connection variables
## https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#connection-variables
ansible_host: 192.168.1.11
ansible_python_interpreter: /usr/bin/python3.11

# Static DHCP IP assignment variables used by pfsense firewall task
dhcp:
  wired:
    mac_address: 'a5:5c:40:3b:f1:h3'
    client_identifier: 'macbook:f1h3'
    ip_address: 192.168.1.11
    hostname: 'macbook'
    description: 'macbook wired interface'
    interface: 'lan'
    dnsserver: ''
  wifi:
    mac_address: 'a5:5c:40:3b:f1:h4'
    client_identifier: 'macbook:f1h4'
    ip_address: 192.168.1.12
    hostname: 'macbook'
    description: 'macbook wifi interface'
    interface: 'lan'
    dnsserver: ''